name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1

      # Step 3: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Import existing resource group (non-interactive)
      - name: Terraform Import Resource Group
        run: |
          terraform import \
            -input=false \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            azurerm_resource_group.rg_securenetwork \
            /subscriptions/ec248675-1d06-41c0-a954-557ab9cf7127/resourceGroups/Secure-Network || true

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
