name: Secure-network Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Use local .env if exists, otherwise fallback to GitHub Secrets
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Load local .env
      - name: Load .env
        if: ${{ runner.os != 'Windows' }}
        run: |
          if [ -f .env ]; then
            echo "Loading .env variables..."
            export $(grep -v '^#' .env | xargs)
          fi

      # 3. Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Set Terraform Azure environment variables
      - name: Set Terraform Azure env
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      # 5. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 6. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 7a. Import existing Resource Group
      - name: Terraform Import existing RG
        run: |
          terraform import azurerm_resource_group.rg_securenetwork /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network || true

      # 7b. Import existing Virtual Networks
      - name: Terraform Import existing VNETs
        run: |
          terraform import azurerm_virtual_network.vnet1 /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/virtualNetworks/Peer1_vnet || true
          terraform import azurerm_virtual_network.vnet2 /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/virtualNetworks/Peer2_vnet || true

      # 7c. Import existing Public IPs
      - name: Terraform Import existing Public IPs
        run: |
          terraform import azurerm_public_ip.peer1_pub /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/publicIPAddresses/peer1-public-ip || true
          terraform import azurerm_public_ip.peer2_pub /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/publicIPAddresses/peer2-public-ip || true

      # 7d. Import existing NSGs
      - name: Terraform Import existing NSGs
        run: |
          terraform import azurerm_network_security_group.peer1_nsg /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/networkSecurityGroups/peer1-nsg || true
          terraform import azurerm_network_security_group.peer2_nsg /subscriptions/${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}/resourceGroups/Secure-Network/providers/Microsoft.Network/networkSecurityGroups/peer2-nsg || true

      # 8. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # 9. Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 10. Apply Terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
