name: Secure-network

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Create SSH public key file
    - name: Create SSH public key file
      run: |
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > secure_network_key.pub

    # 5. Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # 6. Validate Terraform
    - name: Terraform Validate
      run: terraform validate

    # 7. Plan Terraform
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # 8. Apply Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
